// *****************************************************************************
// * Copyright (c) 2020, 2021, 2022 joshua.tee@gmail.com. All rights reserved.
// *
// * Refer to the COPYING file of the official project for license.
// *****************************************************************************

using Gee;

class GlobalArrays {

    public static string[] getRadars() {
        var radarList = new ArrayList<string>();
        radarList.add_all(UtilityList.wrap(radars));
        radarList.add_all(UtilityList.wrap(tdwrRadars));
        return radarList.to_array();
    }

    public static int findRadarIndex(string radarF) {
        print("findRadarIndex " + radarF + "\n");
        var radar = radarF;
        var radarList = new ArrayList<string>();
        radarList.add_all(UtilityList.wrap(radars));
        radarList.add_all(UtilityList.wrap(tdwrRadars));
        foreach (var index in range(radarList.size)) {
            if (radarList[index].has_prefix(radar + ":")) {
                return index;
            }
        }
        return 0;
    }

    public static ArrayList<string> tdwrRadarCodes() {
        var radarList = new ArrayList<string>();
        foreach (var radar in tdwrRadars) {
            radarList.add(radar.split(":")[0]);
        }
        return radarList;
    }

    public static ArrayList<string> nexradRadarCodes() {
        var radarList = new ArrayList<string>();
        foreach (var radar in radars) {
            radarList.add(radar.split(":")[0]);
        }
        return radarList;
    }

    public const string[] states = {
        "AL: Alabama",
        "AK: Alaska",
        "AZ: Arizona",
        "AR: Arkansas",
        "CA: California",
        "CO: Colorado",
        "CT: Connecticut",
        "DE: Delaware",
        "FL: Florida",
        "GA: Georgia",
        "HI: Hawaii",
        "ID: Idaho",
        "IL: Illinois",
        "IN: Indiana",
        "IA: Iowa",
        "KS: Kansas",
        "KY: Kentucky",
        "LA: Louisiana",
        "ME: Maine",
        "MD: Maryland",
        "MA: Massachusetts",
        "MI: Michigan",
        "MN: Minnesota",
        "MS: Mississippi",
        "MO: Missouri",
        "MT: Montana",
        "NE: Nebraska",
        "NV: Nevada",
        "NH: New Hampshire",
        "NJ: New Jersey",
        "NM: New Mexico",
        "NY: New York",
        "NC: North Carolina",
        "ND: North Dakota",
        "OH: Ohio",
        "OK: Oklahoma",
        "OR: Oregon",
        "PA: Pennsylvania",
        "RI: Rhode Island",
        "SC: South Carolina",
        "SD: South Dakota",
        "TN: Tennessee",
        "TX: Texas",
        "UT: Utah",
        "VT: Vermont",
        "VA: Virginia",
        "WA: Washington",
        "WV: West Virginia",
        "WI: Wisconsin",
        "WY: Wyoming"
    };

    public const string[] wfos = {
        "AFC: AK, Anchorage",
        "AFG: AK, Fairbanks",
        "AJK: AK, Juneau",
        "BMX: AL, Birmingham",
        "HUN: AL, Huntsville",
        "MOB: AL, Mobile",
        "LZK: AR, Little Rock",
        "FGZ: AZ, Flagstaff",
        "PSR: AZ, Phoenix",
        "TWC: AZ, Tucson",
        "EKA: CA, Eureka",
        "HNX: CA, Hanford",
        "LOX: CA, Los Angeles",
        "MTR: CA, San Francisco",
        "SGX: CA, San Diego",
        "STO: CA, Sacramento",
        "BOU: CO, Denver/Boulder",
        "GJT: CO, Grand Junction",
        "PUB: CO, Pueblo",
        "JAX: FL, Jacksonville",
        "KEY: FL, Key West",
        "MFL: FL, Miami",
        "MLB: FL, Melbourne",
        "TAE: FL, Tallahassee",
        "TBW: FL, Tampa Bay Area",
        "FFC: GA, Atlanta",
        "GUM: GU, Guam",
        "HFO: HI, Honolulu",
        "DMX: IA, Des Moines",
        "DVN: IA, Quad Cities",
        "BOI: ID, Boise",
        "PIH: ID, Pocatello",
        "ILX: IL, Lincoln",
        "LOT: IL, Chicago",
        "IND: IN, Indianapolis",
        "IWX: IN, Nrn. Indiana",
        "DDC: KS, Dodge City",
        "GLD: KS, Goodland",
        "ICT: KS, Wichita",
        "TOP: KS, Topeka",
        "JKL: KY, Jackson",
        "LMK: KY, Louisville",
        "PAH: KY, Paducah",
        "LCH: LA, Lake Charles",
        "HDC: LA, Hammond",
        "SHV: LA, Shreveport",
        "BOX: MA, Boston",
        "CAR: ME, Caribou",
        "GYX: ME, Gray",
        "APX: MI, Gaylord",
        "DTX: MI, Detroit",
        "GRR: MI, Grand Rapids",
        "MQT: MI, Marquette",
        "DLH: MN, Duluth",
        "MPX: MN, Twin Cities",
        "EAX: MO, Kansas City",
        "LSX: MO, St. Louis",
        "SGF: MO, Springfield",
        "JAN: MS, Jackson",
        "BYZ: MT, Billings",
        "GGW: MT, Glasgow",
        "MSO: MT, Missoula",
        "TFX: MT, Great Falls",
        "ILM: NC, Wilmington",
        "MHX: NC, Morehead City",
        "RAH: NC, Raleigh",
        "BIS: ND, Bismarck",
        "FGF: ND, Grand Forks",
        "GID: NE, Hastings",
        "LBF: NE, North Platte",
        "OAX: NE, Omaha",
        "PHI: NJ, Mount Holly",
        "ABQ: NM, Albuquerque",
        "LKN: NV, Elko",
        "REV: NV, Reno",
        "VEF: NV, Las Vegas",
        "ALY: NY, Albany",
        "BGM: NY, Binghamton",
        "BUF: NY, Buffalo",
        "OKX: NY, New York City",
        "CLE: OH, Cleveland",
        "ILN: OH, Wilmington",
        "OUN: OK, Norman",
        "TSA: OK, Tulsa",
        "MFR: OR, Medford",
        "PDT: OR, Pendleton",
        "PQR: OR, Portland",
        "CTP: PA, State College",
        "PBZ: PA, Pittsburgh",
        "SJU: PR, San Juan",
        "CAE: SC, Columbia",
        "CHS: SC, Charleston",
        "GSP: SC, Greer",
        "ABR: SD, Aberdeen",
        "FSD: SD, Sioux Falls",
        "UNR: SD, Rapid City",
        "MEG: TN, Memphis",
        "MRX: TN, Morristown",
        "OHX: TN, Nashville",
        "AMA: TX, Amarillo",
        "BRO: TX, Brownsville",
        "CRP: TX, Corpus Christi",
        "EPZ: TX, El Paso",
        "EWX: TX, Austin/San Antonio",
        "FWD: TX, Dallas/Fort Worth",
        "HGX: TX, Houston",
        "LUB: TX, Lubbock",
        "MAF: TX, Midland/Odessa",
        "SJT: TX, San Angelo",
        "SLC: UT, Salt Lake City",
        "AKQ: VA, Wakefield",
        "LWX: VA, Sterling",
        "RNK: VA, Blacksburg",
        "BTV: VT, Burlington",
        "OTX: WA, Spokane",
        "SEW: WA, Seattle",
        "ARX: WI, La Crosse",
        "GRB: WI, Green Bay",
        "MKX: WI, Milwaukee",
        "RLX: WV, Charleston",
        "CYS: WY, Cheyenne",
        "RIW: WY, Riverton"
    };

    public const string[] radars = {
        "PABC: AK, Bethel",
        "PAPD: AK, Fairbanks/Pedro Dome",
        "PAHG: AK, Kenai",
        "PAKC: AK, King Salmon",
        "PAIH: AK, Middleton Island",
        "PAEC: AK, Nome",
        "PACG: AK, Sitka/Biorka Island",
        "KBMX: AL, Birmingham",
        "KEOX: AL, Fort Rucker",
        "KHTX: AL, Huntsville",
        "KMXX: AL, Maxwell AFB",
        "KMOB: AL, Mobile",
        "KSRX: AR, Fort Smith",
        "KLZK: AR, Little Rock",
        "KFSX: AZ, Flagstaff",
        "KIWA: AZ, Phoenix",
        "KEMX: AZ, Tucson",
        "KYUX: AZ, Yuma",
        "KBBX: CA, Beale AFB",
        "KEYX: CA, Edwards AFB",
        "KBHX: CA, Eureka",
        "KVTX: CA, Los Angeles",
        "KDAX: CA, Sacramento",
        "KNKX: CA, San Diego",
        "KMUX: CA, San Francisco",
        "KHNX: CA, San Joaquin Valley",
        "KSOX: CA, Santa Ana Mountains",
        "KVBX: CA, Vandenberg AFB",
        "KFTG: CO, Denver",
        "KGJX: CO, Grand Junction",
        "KPUX: CO, Pueblo",
        "KDOX: DE, Dover AFB",
        "KEVX: FL, Eglin AFB",
        "KJAX: FL, Jacksonville",
        "KBYX: FL, Key West",
        "KMLB: FL, Melbourne",
        "KAMX: FL, Miami",
        "KTLH: FL, Tallahassee",
        "KTBW: FL, Tampa",
        "KFFC: GA, Atlanta",
        "KVAX: GA, Moody AFB",
        "KJGX: GA, Robins AFB",
        "PGUA: GU, Andersen AFB",
        "PHKI: HI, Kauai",
        "PHKM: HI, Kohala",
        "PHMO: HI, Molokai",
        "PHWA: HI, South Shore",
        "KDVN: IA, Davenport",
        "KDMX: IA, Des Moines",
        "KCBX: ID, Boise",
        "KSFX: ID, Pocatello/Idaho Falls",
        "KLOT: IL, Chicago",
        "KILX: IL, Lincoln",
        "KVWX: IN, Evansville",
        "KIND: IN, Indianapolis",
        "KIWX: IN, North Webster",
        "KDDC: KS, Dodge City",
        "KGLD: KS, Goodland",
        "KTWX: KS, Topeka",
        "KICT: KS, Wichita",
        "KHPX: KY, Fort Campbell",
        "KJKL: KY, Jackson",
        "KLVX: KY, Louisville",
        "KPAH: KY, Paducah",
        "KPOE: LA, Fort Polk",
        "KLCH: LA, Lake Charles",
        "KLIX: LA, New Orleans",
        "KSHV: LA, Shreveport",
        "KBOX: MA, Boston",
        "KCBW: ME, Loring AFB",
        "KGYX: ME, Portland",
        "KDTX: MI, Detroit/Pontiac",
        "KAPX: MI, Gaylord",
        "KGRR: MI, Grand Rapids",
        "KMQT: MI, Marquette",
        "KDLH: MN, Duluth",
        "KMPX: MN, Minneapolis/St. Paul",
        "KEAX: MO, Kansas City",
        "KSGF: MO, Springfield",
        "KLSX: MO, St. Louis",
        "KDGX: MS, Brandon/Jackson",
        "KGWX: MS, Columbus AFB",
        "KBLX: MT, Billings",
        "KGGW: MT, Glasgow",
        "KTFX: MT, Great Falls",
        "KMSX: MT, Missoula",
        "KMHX: NC, Morehead City",
        "KRAX: NC, Raleigh/Durham",
        "KLTX: NC, Wilmington",
        "KBIS: ND, Bismarck",
        "KMVX: ND, Grand Forks (Mayville)",
        "KMBX: ND, Minot AFB",
        "KUEX: NE, Grand Island/Hastings",
        "KLNX: NE, North Platte",
        "KOAX: NE, Omaha",
        "KABX: NM, Albuquerque",
        "KFDX: NM, Cannon AFB",
        "KHDX: NM, Holloman AFB",
        "KLRX: NV, Elko",
        "KESX: NV, Las Vegas",
        "KRGX: NV, Reno",
        "KENX: NY, Albany",
        "KBGM: NY, Binghamton",
        "KBUF: NY, Buffalo",
        "KTYX: NY, Montague",
        "KOKX: NY, New York City",
        "KCLE: OH, Cleveland",
        "KILN: OH, Wilmington",
        "KFDR: OK, Frederick",
        "KTLX: OK, Oklahoma City",
        "KINX: OK, Tulsa",
        "KVNX: OK, Vance AFB",
        "KMAX: OR, Medford",
        "KPDT: OR, Pendleton",
        "KRTX: OR, Portland",
        "KDIX: PA, Philadelphia",
        "KPBZ: PA, Pittsburgh",
        "KCCX: PA, State College",
        "TJUA: PR, San Juan",
        "KCLX: SC, Charleston",
        "KCAE: SC, Columbia",
        "KGSP: SC, Greer",
        "KABR: SD, Aberdeen",
        "KUDX: SD, Rapid City",
        "KFSD: SD, Sioux Falls",
        "KMRX: TN, Knoxville/Tri Cities",
        "KNQA: TN, Memphis",
        "KOHX: TN, Nashville",
        "KAMA: TX, Amarillo",
        "KEWX: TX, Austin/San Antonio",
        "KBRO: TX, Brownsville",
        "KCRP: TX, Corpus Christi",
        "KFWS: TX, Dallas/Ft. Worth",
        "KDYX: TX, Dyess AFB",
        "KEPZ: TX, El Paso",
        "KGRK: TX, Fort Hood",
        "KHGX: TX, Houston/Galveston",
        "KDFX: TX, Laughlin AFB",
        "KLBB: TX, Lubbock",
        "KMAF: TX, Midland/Odessa",
        "KSJT: TX, San Angelo",
        "KICX: UT, Cedar City",
        "KMTX: UT, Salt Lake City",
        "KAKQ: VA, Norfolk/Richmond",
        "KFCX: VA, Roanoke",
        "KLWX: VA, Sterling",
        "KCXX: VT, Burlington",
        "KLGX: WA, Langley Hill",
        "KATX: WA, Seattle/Tacoma",
        "KOTX: WA, Spokane",
        "KGRB: WI, Green Bay",
        "KARX: WI, La Crosse",
        "KMKX: WI, Milwaukee",
        "KRLX: WV, Charleston",
        "KCYS: WY, Cheyenne",
        "KRIW: WY, Riverton"
    };

    public const string[] tdwrRadars = {
        "TPHX: AZ, Phoenix",
        "TDEN: CO, Denver",
        "TFLL: FL, Fort Lauderdale",
        "TMIA: FL, Miami",
        "TMCO: FL, Orlando International",
        "TTPA: FL, Tampa Bay",
        "TPBI: FL, West Palm Beach",
        "TATL: GA, Atlanta",
        "TMDW: IL, Chicago Midway",
        "TORD: IL, Chicago O\"Hare",
        "TIDS: IN, Indianapolis",
        "TICH: KS, Wichita",
        "TSDF: KY, Louisville",
        "TMSY: LA, New Orleans",
        "TBOS: MA, Boston",
        "TBWI: MD, Baltimore/Wash",
        "TDCA: MD, Washington National",
        "TDTW: MI, Detroit",
        "TMSP: MN, Minneapolis",
        "TMCI: MO, Kansas City",
        "TSTL: MO, St Louis",
        "TCLT: NC, Charlotte",
        "TRDU: NC, Raleigh Durham",
        "TEWR: NJ, Newark",
        "TLAS: NV, Las Vegas",
        "TJFK: NY, New York City",
        "TLVE: OH, Cleveland",
        "TCMH: OH, Columbus",
        "TCVG: OH, Covington",
        "TDAY: OH, Dayton",
        "TOKC: OK, Oklahoma City",
        "TTUL: OK, Tulsa",
        "TPHL: PA, Philadelphia",
        "TPIT: PA, Pittsburgh",
        "TSJU: PR, San Juan",
        "TMEM: TN, Memphis",
        "TBNA: TN, Nashville",
        "TDFW: TX, Dallas/Ft. Worth",
        "TDAL: TX, Dallas Love Field",
        "THOU: TX, Houston Hobby",
        "TIAH: TX, Houston International",
        "TSLC: UT, Salt Lake City",
        "TIAD: VA, Dulles",
        "TMKE: WI, Milwaukee"
    };
}
